### ISSUE TITLE
Enhancements for `fs-index` Crate

### ISSUE THREAD

**Issue by tareknaser** [ARK-Builders/ark-core#31]
**This is a tracking issue for brainstorming ideas to enhance `fs-index` crate**
---
- [x] `ResourceIndex` exposed API should be as discussed here https://github.com/ARK-Builders/arklib/issues/91#issuecomment-1998887042
- [x] `id_to_resources` should be of type `HashMap<HashType, Vec<IndexedResource>>` instead of `HashMap<ResourceId, CanonicalPathBuf>` because one id can map to multiple resource in case of collisions or same content 
- [x] Revise `ResourceIndex::update()` to rebuild the index and compare with the old index. Benchmarking for this feature should be conducted as per issue #30.
- [x] Implement file system watch and update index functionality as described in #21. 
> The difference between `watch_index` and `ark-cli monitor` is that `watch_index` uses `notify` to only update the index when a file system change is detected, as opposed to rebuilding the index from scratch on a time interval.
- [x] Create examples folder:
    - Include one example showing the normal scenario of creating a new index in a specified path and using the API.
    - Include another example showcasing index watch functionality.
- [x] Benchmark the performance of resource indexing queries and operations as outlined in issue #30.
- [x] Ensure that modules are private and only necessary structs and methods are exported.
- [x] Place unit tests in a separate file instead of `index.rs`.
- [x] Implement a custom `Serialize` implementation for `ResourceIndex` where double mappings are not written.

**Comment by kirillt** [comment]
It seems that all sub-issues have been addressed.

Great work, thanks!
